runtime:
  cache_dir: ./.cache/antora

site:
  title: Learning Distributing Tracing 101
  url: https://ibm-cloud-architecture.github.io/learning-distributed-tracing-101/
  start_page: docs::index.adoc

content:
  sources:
    - url: https://github.com/ibm-cloud-architecture/learning-distributed-tracing-101.git
      branches: "master"
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
