version: 2
jobs:
  antora:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - run:
          name: Install Antora and its dependencies
          command: |
            yarn global add @antora/cli@2.0
            yarn global add @antora/site-generator-default@2.0
      - run:
          name: Build docs
          command: antora --pull --stacktrace site.yml
      - persist_to_workspace:
          root: gh-pages
          paths:
            - "*"
  antora-pr:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - run:
          name: Install Antora and its dependencies
          command: |
            yarn global add @antora/cli@2.0
            yarn global add @antora/site-generator-default@2.0
      - run:
          name: Build docs
          command: antora --pull --stacktrace site-dev.yml
      - persist_to_workspace:
          root: gh-pages
          paths:
            - "*"
  site-deploy:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - attach_workspace:
          at: gh-pages
      - run:
          name: Disable jekyll builds
          command: touch gh-pages/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            yarn  global add gh-pages@2.0.1
            git config user.email "csantana@us.ibm.com"
            git config user.name "Carlos Santana"
      - add_ssh_keys:
          fingerprints:
            - "89:d9:91:5b:00:b4:3e:38:87:cd:4c:e2:e3:c9:f1:81"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Publishing new documentation" --dist gh-pages
workflows:
  version: 2
  build:
    jobs:
      - antora-pr
      - antora:
          filters:
            branches:
              only:
                - master
      - site-deploy:
          requires:
            - antora
          filters:
            branches:
              only: master
